#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.233
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SicilNet.Islemler
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TahaZiraat")]
	public partial class IslemlerDataLinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertsiciller(siciller instance);
    partial void Updatesiciller(siciller instance);
    partial void Deletesiciller(siciller instance);
    #endregion
		
		public IslemlerDataLinqDataContext() : 
				base(global::SicilNet.Properties.Settings.Default.SicilBaglantiSatiri, mappingSource)
		{
			OnCreated();
		}
		
		public IslemlerDataLinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IslemlerDataLinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IslemlerDataLinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IslemlerDataLinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<siciller> sicillers
		{
			get
			{
				return this.GetTable<siciller>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.siciller")]
	public partial class siciller : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _UYE_ID;
		
		private string _UYE_KOD;
		
		private string _UYE_MAHALLE;
		
		private string _UYE_SOYADI;
		
		private string _UYE_ADI;
		
		private string _UYE_BABA;
		
		private string _UYE_YERI;
		
		private System.Nullable<System.DateTime> _UYE_DOGUMTRH;
		
		private string _UYE_N_IL;
		
		private string _UYE_N_ILCE;
		
		private System.Nullable<System.DateTime> _UYE_GIRISTRH;
		
		private System.Nullable<System.DateTime> _UYE_CIKISTRH;
		
		private string _UYE_MEDENIHAL;
		
		private string _UYE_MEZUNIYET;
		
		private string _UYE_DERECE;
		
		private string _UYE_K_ILI;
		
		private string _UYE_K_ILCE;
		
		private string _UYE_K_KAYITYER;
		
		private string _UYE_K_CILTNO;
		
		private string _UYE_VERILDIGIYR;
		
		private string _UYE_VEZNE;
		
		private string _UYE_K_KUTNO;
		
		private System.Nullable<System.DateTime> _UYE_CTARIHI;
		
		private string _UYE_ENO;
		
		private string _UYE_ANNE;
		
		private string _UYE_DNYR;
		
		private string _UYE_BAGKURNO;
		
		private string _UYE_VERGINO;
		
		private string _UYE_TRK;
		
		private string _UYE_CINSIYET;
		
		private string _UYE_MERNISNO;
		
		private string _UYE_KULLANICI;
		
		private string _UYE_A_TARIH;
		
		private string _UYE_BUCAGI;
		
		private string _UYE_ALANKODU;
		
		private string _UYE_SABITTEL;
		
		private string _UYE_ADRESI;
		
		private string _UYE_SIGORTA;
		
		private string _UYE_MHKAPNO;
		
		private System.Nullable<bool> _UYE_DURUMU;
		
		private System.Nullable<System.DateTime> _UYE_YONKURTARSIL;
		
		private string _UYE_YONKARNOSIL;
		
		private System.Nullable<System.DateTime> _UYE_YONKURTARKYT;
		
		private string _UYE_YONKURNOKYT;
		
		private string _UYE_ODANO;
		
		private System.Nullable<int> _UYE_BAKTIGIKIZ;
		
		private string _UYE_KAYITTURU;
		
		private System.Nullable<System.DateTime> _UYE_SONBEYANTRH;
		
		private string _UYE_UYRUK;
		
		private string _UYE_CEPTELEFON;
		
		private string _UYE_AYRILISACIKLAMA;
		
		private string _UYE_GNSACIKLAMA;
		
		private string _UYE_GMAHALLE;
		
		private string _UYE_SIRANOG;
		
		private string _UYE_SMSGRUP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUYE_IDChanging(long value);
    partial void OnUYE_IDChanged();
    partial void OnUYE_KODChanging(string value);
    partial void OnUYE_KODChanged();
    partial void OnUYE_MAHALLEChanging(string value);
    partial void OnUYE_MAHALLEChanged();
    partial void OnUYE_SOYADIChanging(string value);
    partial void OnUYE_SOYADIChanged();
    partial void OnUYE_ADIChanging(string value);
    partial void OnUYE_ADIChanged();
    partial void OnUYE_BABAChanging(string value);
    partial void OnUYE_BABAChanged();
    partial void OnUYE_YERIChanging(string value);
    partial void OnUYE_YERIChanged();
    partial void OnUYE_DOGUMTRHChanging(System.Nullable<System.DateTime> value);
    partial void OnUYE_DOGUMTRHChanged();
    partial void OnUYE_N_ILChanging(string value);
    partial void OnUYE_N_ILChanged();
    partial void OnUYE_N_ILCEChanging(string value);
    partial void OnUYE_N_ILCEChanged();
    partial void OnUYE_GIRISTRHChanging(System.Nullable<System.DateTime> value);
    partial void OnUYE_GIRISTRHChanged();
    partial void OnUYE_CIKISTRHChanging(System.Nullable<System.DateTime> value);
    partial void OnUYE_CIKISTRHChanged();
    partial void OnUYE_MEDENIHALChanging(string value);
    partial void OnUYE_MEDENIHALChanged();
    partial void OnUYE_MEZUNIYETChanging(string value);
    partial void OnUYE_MEZUNIYETChanged();
    partial void OnUYE_DERECEChanging(string value);
    partial void OnUYE_DERECEChanged();
    partial void OnUYE_K_ILIChanging(string value);
    partial void OnUYE_K_ILIChanged();
    partial void OnUYE_K_ILCEChanging(string value);
    partial void OnUYE_K_ILCEChanged();
    partial void OnUYE_K_KAYITYERChanging(string value);
    partial void OnUYE_K_KAYITYERChanged();
    partial void OnUYE_K_CILTNOChanging(string value);
    partial void OnUYE_K_CILTNOChanged();
    partial void OnUYE_VERILDIGIYRChanging(string value);
    partial void OnUYE_VERILDIGIYRChanged();
    partial void OnUYE_VEZNEChanging(string value);
    partial void OnUYE_VEZNEChanged();
    partial void OnUYE_K_KUTNOChanging(string value);
    partial void OnUYE_K_KUTNOChanged();
    partial void OnUYE_CTARIHIChanging(System.Nullable<System.DateTime> value);
    partial void OnUYE_CTARIHIChanged();
    partial void OnUYE_ENOChanging(string value);
    partial void OnUYE_ENOChanged();
    partial void OnUYE_ANNEChanging(string value);
    partial void OnUYE_ANNEChanged();
    partial void OnUYE_DNYRChanging(string value);
    partial void OnUYE_DNYRChanged();
    partial void OnUYE_BAGKURNOChanging(string value);
    partial void OnUYE_BAGKURNOChanged();
    partial void OnUYE_VERGINOChanging(string value);
    partial void OnUYE_VERGINOChanged();
    partial void OnUYE_TRKChanging(string value);
    partial void OnUYE_TRKChanged();
    partial void OnUYE_CINSIYETChanging(string value);
    partial void OnUYE_CINSIYETChanged();
    partial void OnUYE_MERNISNOChanging(string value);
    partial void OnUYE_MERNISNOChanged();
    partial void OnUYE_KULLANICIChanging(string value);
    partial void OnUYE_KULLANICIChanged();
    partial void OnUYE_A_TARIHChanging(string value);
    partial void OnUYE_A_TARIHChanged();
    partial void OnUYE_BUCAGIChanging(string value);
    partial void OnUYE_BUCAGIChanged();
    partial void OnUYE_ALANKODUChanging(string value);
    partial void OnUYE_ALANKODUChanged();
    partial void OnUYE_SABITTELChanging(string value);
    partial void OnUYE_SABITTELChanged();
    partial void OnUYE_ADRESIChanging(string value);
    partial void OnUYE_ADRESIChanged();
    partial void OnUYE_SIGORTAChanging(string value);
    partial void OnUYE_SIGORTAChanged();
    partial void OnUYE_MHKAPNOChanging(string value);
    partial void OnUYE_MHKAPNOChanged();
    partial void OnUYE_DURUMUChanging(System.Nullable<bool> value);
    partial void OnUYE_DURUMUChanged();
    partial void OnUYE_YONKURTARSILChanging(System.Nullable<System.DateTime> value);
    partial void OnUYE_YONKURTARSILChanged();
    partial void OnUYE_YONKARNOSILChanging(string value);
    partial void OnUYE_YONKARNOSILChanged();
    partial void OnUYE_YONKURTARKYTChanging(System.Nullable<System.DateTime> value);
    partial void OnUYE_YONKURTARKYTChanged();
    partial void OnUYE_YONKURNOKYTChanging(string value);
    partial void OnUYE_YONKURNOKYTChanged();
    partial void OnUYE_ODANOChanging(string value);
    partial void OnUYE_ODANOChanged();
    partial void OnUYE_BAKTIGIKIZChanging(System.Nullable<int> value);
    partial void OnUYE_BAKTIGIKIZChanged();
    partial void OnUYE_KAYITTURUChanging(string value);
    partial void OnUYE_KAYITTURUChanged();
    partial void OnUYE_SONBEYANTRHChanging(System.Nullable<System.DateTime> value);
    partial void OnUYE_SONBEYANTRHChanged();
    partial void OnUYE_UYRUKChanging(string value);
    partial void OnUYE_UYRUKChanged();
    partial void OnUYE_CEPTELEFONChanging(string value);
    partial void OnUYE_CEPTELEFONChanged();
    partial void OnUYE_AYRILISACIKLAMAChanging(string value);
    partial void OnUYE_AYRILISACIKLAMAChanged();
    partial void OnUYE_GNSACIKLAMAChanging(string value);
    partial void OnUYE_GNSACIKLAMAChanged();
    partial void OnUYE_GMAHALLEChanging(string value);
    partial void OnUYE_GMAHALLEChanged();
    partial void OnUYE_SIRANOGChanging(string value);
    partial void OnUYE_SIRANOGChanged();
    partial void OnUYE_SMSGRUPChanging(string value);
    partial void OnUYE_SMSGRUPChanged();
    #endregion
		
		public siciller()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long UYE_ID
		{
			get
			{
				return this._UYE_ID;
			}
			set
			{
				if ((this._UYE_ID != value))
				{
					this.OnUYE_IDChanging(value);
					this.SendPropertyChanging();
					this._UYE_ID = value;
					this.SendPropertyChanged("UYE_ID");
					this.OnUYE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_KOD", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UYE_KOD
		{
			get
			{
				return this._UYE_KOD;
			}
			set
			{
				if ((this._UYE_KOD != value))
				{
					this.OnUYE_KODChanging(value);
					this.SendPropertyChanging();
					this._UYE_KOD = value;
					this.SendPropertyChanged("UYE_KOD");
					this.OnUYE_KODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_MAHALLE", DbType="VarChar(4)")]
		public string UYE_MAHALLE
		{
			get
			{
				return this._UYE_MAHALLE;
			}
			set
			{
				if ((this._UYE_MAHALLE != value))
				{
					this.OnUYE_MAHALLEChanging(value);
					this.SendPropertyChanging();
					this._UYE_MAHALLE = value;
					this.SendPropertyChanged("UYE_MAHALLE");
					this.OnUYE_MAHALLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_SOYADI", DbType="VarChar(30)")]
		public string UYE_SOYADI
		{
			get
			{
				return this._UYE_SOYADI;
			}
			set
			{
				if ((this._UYE_SOYADI != value))
				{
					this.OnUYE_SOYADIChanging(value);
					this.SendPropertyChanging();
					this._UYE_SOYADI = value;
					this.SendPropertyChanged("UYE_SOYADI");
					this.OnUYE_SOYADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_ADI", DbType="VarChar(30)")]
		public string UYE_ADI
		{
			get
			{
				return this._UYE_ADI;
			}
			set
			{
				if ((this._UYE_ADI != value))
				{
					this.OnUYE_ADIChanging(value);
					this.SendPropertyChanging();
					this._UYE_ADI = value;
					this.SendPropertyChanged("UYE_ADI");
					this.OnUYE_ADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_BABA", DbType="VarChar(30)")]
		public string UYE_BABA
		{
			get
			{
				return this._UYE_BABA;
			}
			set
			{
				if ((this._UYE_BABA != value))
				{
					this.OnUYE_BABAChanging(value);
					this.SendPropertyChanging();
					this._UYE_BABA = value;
					this.SendPropertyChanged("UYE_BABA");
					this.OnUYE_BABAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_YERI", DbType="VarChar(40)")]
		public string UYE_YERI
		{
			get
			{
				return this._UYE_YERI;
			}
			set
			{
				if ((this._UYE_YERI != value))
				{
					this.OnUYE_YERIChanging(value);
					this.SendPropertyChanging();
					this._UYE_YERI = value;
					this.SendPropertyChanged("UYE_YERI");
					this.OnUYE_YERIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_DOGUMTRH", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> UYE_DOGUMTRH
		{
			get
			{
				return this._UYE_DOGUMTRH;
			}
			set
			{
				if ((this._UYE_DOGUMTRH != value))
				{
					this.OnUYE_DOGUMTRHChanging(value);
					this.SendPropertyChanging();
					this._UYE_DOGUMTRH = value;
					this.SendPropertyChanged("UYE_DOGUMTRH");
					this.OnUYE_DOGUMTRHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_N_IL", DbType="VarChar(20)")]
		public string UYE_N_IL
		{
			get
			{
				return this._UYE_N_IL;
			}
			set
			{
				if ((this._UYE_N_IL != value))
				{
					this.OnUYE_N_ILChanging(value);
					this.SendPropertyChanging();
					this._UYE_N_IL = value;
					this.SendPropertyChanged("UYE_N_IL");
					this.OnUYE_N_ILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_N_ILCE", DbType="VarChar(20)")]
		public string UYE_N_ILCE
		{
			get
			{
				return this._UYE_N_ILCE;
			}
			set
			{
				if ((this._UYE_N_ILCE != value))
				{
					this.OnUYE_N_ILCEChanging(value);
					this.SendPropertyChanging();
					this._UYE_N_ILCE = value;
					this.SendPropertyChanged("UYE_N_ILCE");
					this.OnUYE_N_ILCEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_GIRISTRH", DbType="DateTime")]
		public System.Nullable<System.DateTime> UYE_GIRISTRH
		{
			get
			{
				return this._UYE_GIRISTRH;
			}
			set
			{
				if ((this._UYE_GIRISTRH != value))
				{
					this.OnUYE_GIRISTRHChanging(value);
					this.SendPropertyChanging();
					this._UYE_GIRISTRH = value;
					this.SendPropertyChanged("UYE_GIRISTRH");
					this.OnUYE_GIRISTRHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_CIKISTRH", DbType="DateTime")]
		public System.Nullable<System.DateTime> UYE_CIKISTRH
		{
			get
			{
				return this._UYE_CIKISTRH;
			}
			set
			{
				if ((this._UYE_CIKISTRH != value))
				{
					this.OnUYE_CIKISTRHChanging(value);
					this.SendPropertyChanging();
					this._UYE_CIKISTRH = value;
					this.SendPropertyChanged("UYE_CIKISTRH");
					this.OnUYE_CIKISTRHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_MEDENIHAL", DbType="VarChar(10)")]
		public string UYE_MEDENIHAL
		{
			get
			{
				return this._UYE_MEDENIHAL;
			}
			set
			{
				if ((this._UYE_MEDENIHAL != value))
				{
					this.OnUYE_MEDENIHALChanging(value);
					this.SendPropertyChanging();
					this._UYE_MEDENIHAL = value;
					this.SendPropertyChanged("UYE_MEDENIHAL");
					this.OnUYE_MEDENIHALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_MEZUNIYET", DbType="VarChar(15)")]
		public string UYE_MEZUNIYET
		{
			get
			{
				return this._UYE_MEZUNIYET;
			}
			set
			{
				if ((this._UYE_MEZUNIYET != value))
				{
					this.OnUYE_MEZUNIYETChanging(value);
					this.SendPropertyChanging();
					this._UYE_MEZUNIYET = value;
					this.SendPropertyChanged("UYE_MEZUNIYET");
					this.OnUYE_MEZUNIYETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_DERECE", DbType="VarChar(1)")]
		public string UYE_DERECE
		{
			get
			{
				return this._UYE_DERECE;
			}
			set
			{
				if ((this._UYE_DERECE != value))
				{
					this.OnUYE_DERECEChanging(value);
					this.SendPropertyChanging();
					this._UYE_DERECE = value;
					this.SendPropertyChanged("UYE_DERECE");
					this.OnUYE_DERECEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_K_ILI", DbType="VarChar(20)")]
		public string UYE_K_ILI
		{
			get
			{
				return this._UYE_K_ILI;
			}
			set
			{
				if ((this._UYE_K_ILI != value))
				{
					this.OnUYE_K_ILIChanging(value);
					this.SendPropertyChanging();
					this._UYE_K_ILI = value;
					this.SendPropertyChanged("UYE_K_ILI");
					this.OnUYE_K_ILIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_K_ILCE", DbType="VarChar(20)")]
		public string UYE_K_ILCE
		{
			get
			{
				return this._UYE_K_ILCE;
			}
			set
			{
				if ((this._UYE_K_ILCE != value))
				{
					this.OnUYE_K_ILCEChanging(value);
					this.SendPropertyChanging();
					this._UYE_K_ILCE = value;
					this.SendPropertyChanged("UYE_K_ILCE");
					this.OnUYE_K_ILCEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_K_KAYITYER", DbType="VarChar(20)")]
		public string UYE_K_KAYITYER
		{
			get
			{
				return this._UYE_K_KAYITYER;
			}
			set
			{
				if ((this._UYE_K_KAYITYER != value))
				{
					this.OnUYE_K_KAYITYERChanging(value);
					this.SendPropertyChanging();
					this._UYE_K_KAYITYER = value;
					this.SendPropertyChanged("UYE_K_KAYITYER");
					this.OnUYE_K_KAYITYERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_K_CILTNO", DbType="VarChar(20)")]
		public string UYE_K_CILTNO
		{
			get
			{
				return this._UYE_K_CILTNO;
			}
			set
			{
				if ((this._UYE_K_CILTNO != value))
				{
					this.OnUYE_K_CILTNOChanging(value);
					this.SendPropertyChanging();
					this._UYE_K_CILTNO = value;
					this.SendPropertyChanged("UYE_K_CILTNO");
					this.OnUYE_K_CILTNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_VERILDIGIYR", DbType="VarChar(20)")]
		public string UYE_VERILDIGIYR
		{
			get
			{
				return this._UYE_VERILDIGIYR;
			}
			set
			{
				if ((this._UYE_VERILDIGIYR != value))
				{
					this.OnUYE_VERILDIGIYRChanging(value);
					this.SendPropertyChanging();
					this._UYE_VERILDIGIYR = value;
					this.SendPropertyChanged("UYE_VERILDIGIYR");
					this.OnUYE_VERILDIGIYRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_VEZNE", DbType="VarChar(20)")]
		public string UYE_VEZNE
		{
			get
			{
				return this._UYE_VEZNE;
			}
			set
			{
				if ((this._UYE_VEZNE != value))
				{
					this.OnUYE_VEZNEChanging(value);
					this.SendPropertyChanging();
					this._UYE_VEZNE = value;
					this.SendPropertyChanged("UYE_VEZNE");
					this.OnUYE_VEZNEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_K_KUTNO", DbType="VarChar(10)")]
		public string UYE_K_KUTNO
		{
			get
			{
				return this._UYE_K_KUTNO;
			}
			set
			{
				if ((this._UYE_K_KUTNO != value))
				{
					this.OnUYE_K_KUTNOChanging(value);
					this.SendPropertyChanging();
					this._UYE_K_KUTNO = value;
					this.SendPropertyChanged("UYE_K_KUTNO");
					this.OnUYE_K_KUTNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_CTARIHI", DbType="DateTime")]
		public System.Nullable<System.DateTime> UYE_CTARIHI
		{
			get
			{
				return this._UYE_CTARIHI;
			}
			set
			{
				if ((this._UYE_CTARIHI != value))
				{
					this.OnUYE_CTARIHIChanging(value);
					this.SendPropertyChanging();
					this._UYE_CTARIHI = value;
					this.SendPropertyChanged("UYE_CTARIHI");
					this.OnUYE_CTARIHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_ENO", DbType="VarChar(20)")]
		public string UYE_ENO
		{
			get
			{
				return this._UYE_ENO;
			}
			set
			{
				if ((this._UYE_ENO != value))
				{
					this.OnUYE_ENOChanging(value);
					this.SendPropertyChanging();
					this._UYE_ENO = value;
					this.SendPropertyChanged("UYE_ENO");
					this.OnUYE_ENOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_ANNE", DbType="VarChar(20)")]
		public string UYE_ANNE
		{
			get
			{
				return this._UYE_ANNE;
			}
			set
			{
				if ((this._UYE_ANNE != value))
				{
					this.OnUYE_ANNEChanging(value);
					this.SendPropertyChanging();
					this._UYE_ANNE = value;
					this.SendPropertyChanged("UYE_ANNE");
					this.OnUYE_ANNEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_DNYR", DbType="VarChar(6)")]
		public string UYE_DNYR
		{
			get
			{
				return this._UYE_DNYR;
			}
			set
			{
				if ((this._UYE_DNYR != value))
				{
					this.OnUYE_DNYRChanging(value);
					this.SendPropertyChanging();
					this._UYE_DNYR = value;
					this.SendPropertyChanged("UYE_DNYR");
					this.OnUYE_DNYRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_BAGKURNO", DbType="VarChar(15)")]
		public string UYE_BAGKURNO
		{
			get
			{
				return this._UYE_BAGKURNO;
			}
			set
			{
				if ((this._UYE_BAGKURNO != value))
				{
					this.OnUYE_BAGKURNOChanging(value);
					this.SendPropertyChanging();
					this._UYE_BAGKURNO = value;
					this.SendPropertyChanged("UYE_BAGKURNO");
					this.OnUYE_BAGKURNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_VERGINO", DbType="VarChar(15)")]
		public string UYE_VERGINO
		{
			get
			{
				return this._UYE_VERGINO;
			}
			set
			{
				if ((this._UYE_VERGINO != value))
				{
					this.OnUYE_VERGINOChanging(value);
					this.SendPropertyChanging();
					this._UYE_VERGINO = value;
					this.SendPropertyChanged("UYE_VERGINO");
					this.OnUYE_VERGINOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_TRK", DbType="VarChar(8)")]
		public string UYE_TRK
		{
			get
			{
				return this._UYE_TRK;
			}
			set
			{
				if ((this._UYE_TRK != value))
				{
					this.OnUYE_TRKChanging(value);
					this.SendPropertyChanging();
					this._UYE_TRK = value;
					this.SendPropertyChanged("UYE_TRK");
					this.OnUYE_TRKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_CINSIYET", DbType="VarChar(10)")]
		public string UYE_CINSIYET
		{
			get
			{
				return this._UYE_CINSIYET;
			}
			set
			{
				if ((this._UYE_CINSIYET != value))
				{
					this.OnUYE_CINSIYETChanging(value);
					this.SendPropertyChanging();
					this._UYE_CINSIYET = value;
					this.SendPropertyChanged("UYE_CINSIYET");
					this.OnUYE_CINSIYETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_MERNISNO", DbType="VarChar(12)")]
		public string UYE_MERNISNO
		{
			get
			{
				return this._UYE_MERNISNO;
			}
			set
			{
				if ((this._UYE_MERNISNO != value))
				{
					this.OnUYE_MERNISNOChanging(value);
					this.SendPropertyChanging();
					this._UYE_MERNISNO = value;
					this.SendPropertyChanged("UYE_MERNISNO");
					this.OnUYE_MERNISNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_KULLANICI", DbType="VarChar(25)")]
		public string UYE_KULLANICI
		{
			get
			{
				return this._UYE_KULLANICI;
			}
			set
			{
				if ((this._UYE_KULLANICI != value))
				{
					this.OnUYE_KULLANICIChanging(value);
					this.SendPropertyChanging();
					this._UYE_KULLANICI = value;
					this.SendPropertyChanged("UYE_KULLANICI");
					this.OnUYE_KULLANICIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_A_TARIH", DbType="VarChar(5)")]
		public string UYE_A_TARIH
		{
			get
			{
				return this._UYE_A_TARIH;
			}
			set
			{
				if ((this._UYE_A_TARIH != value))
				{
					this.OnUYE_A_TARIHChanging(value);
					this.SendPropertyChanging();
					this._UYE_A_TARIH = value;
					this.SendPropertyChanged("UYE_A_TARIH");
					this.OnUYE_A_TARIHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_BUCAGI", DbType="VarChar(20)")]
		public string UYE_BUCAGI
		{
			get
			{
				return this._UYE_BUCAGI;
			}
			set
			{
				if ((this._UYE_BUCAGI != value))
				{
					this.OnUYE_BUCAGIChanging(value);
					this.SendPropertyChanging();
					this._UYE_BUCAGI = value;
					this.SendPropertyChanged("UYE_BUCAGI");
					this.OnUYE_BUCAGIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_ALANKODU", DbType="VarChar(3)")]
		public string UYE_ALANKODU
		{
			get
			{
				return this._UYE_ALANKODU;
			}
			set
			{
				if ((this._UYE_ALANKODU != value))
				{
					this.OnUYE_ALANKODUChanging(value);
					this.SendPropertyChanging();
					this._UYE_ALANKODU = value;
					this.SendPropertyChanged("UYE_ALANKODU");
					this.OnUYE_ALANKODUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_SABITTEL", DbType="VarChar(11)")]
		public string UYE_SABITTEL
		{
			get
			{
				return this._UYE_SABITTEL;
			}
			set
			{
				if ((this._UYE_SABITTEL != value))
				{
					this.OnUYE_SABITTELChanging(value);
					this.SendPropertyChanging();
					this._UYE_SABITTEL = value;
					this.SendPropertyChanged("UYE_SABITTEL");
					this.OnUYE_SABITTELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_ADRESI", DbType="VarChar(MAX)")]
		public string UYE_ADRESI
		{
			get
			{
				return this._UYE_ADRESI;
			}
			set
			{
				if ((this._UYE_ADRESI != value))
				{
					this.OnUYE_ADRESIChanging(value);
					this.SendPropertyChanging();
					this._UYE_ADRESI = value;
					this.SendPropertyChanged("UYE_ADRESI");
					this.OnUYE_ADRESIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_SIGORTA", DbType="VarChar(15)")]
		public string UYE_SIGORTA
		{
			get
			{
				return this._UYE_SIGORTA;
			}
			set
			{
				if ((this._UYE_SIGORTA != value))
				{
					this.OnUYE_SIGORTAChanging(value);
					this.SendPropertyChanging();
					this._UYE_SIGORTA = value;
					this.SendPropertyChanged("UYE_SIGORTA");
					this.OnUYE_SIGORTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_MHKAPNO", DbType="VarChar(10)")]
		public string UYE_MHKAPNO
		{
			get
			{
				return this._UYE_MHKAPNO;
			}
			set
			{
				if ((this._UYE_MHKAPNO != value))
				{
					this.OnUYE_MHKAPNOChanging(value);
					this.SendPropertyChanging();
					this._UYE_MHKAPNO = value;
					this.SendPropertyChanged("UYE_MHKAPNO");
					this.OnUYE_MHKAPNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_DURUMU", DbType="Bit")]
		public System.Nullable<bool> UYE_DURUMU
		{
			get
			{
				return this._UYE_DURUMU;
			}
			set
			{
				if ((this._UYE_DURUMU != value))
				{
					this.OnUYE_DURUMUChanging(value);
					this.SendPropertyChanging();
					this._UYE_DURUMU = value;
					this.SendPropertyChanged("UYE_DURUMU");
					this.OnUYE_DURUMUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_YONKURTARSIL", DbType="DateTime")]
		public System.Nullable<System.DateTime> UYE_YONKURTARSIL
		{
			get
			{
				return this._UYE_YONKURTARSIL;
			}
			set
			{
				if ((this._UYE_YONKURTARSIL != value))
				{
					this.OnUYE_YONKURTARSILChanging(value);
					this.SendPropertyChanging();
					this._UYE_YONKURTARSIL = value;
					this.SendPropertyChanged("UYE_YONKURTARSIL");
					this.OnUYE_YONKURTARSILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_YONKARNOSIL", DbType="VarChar(10)")]
		public string UYE_YONKARNOSIL
		{
			get
			{
				return this._UYE_YONKARNOSIL;
			}
			set
			{
				if ((this._UYE_YONKARNOSIL != value))
				{
					this.OnUYE_YONKARNOSILChanging(value);
					this.SendPropertyChanging();
					this._UYE_YONKARNOSIL = value;
					this.SendPropertyChanged("UYE_YONKARNOSIL");
					this.OnUYE_YONKARNOSILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_YONKURTARKYT", DbType="DateTime")]
		public System.Nullable<System.DateTime> UYE_YONKURTARKYT
		{
			get
			{
				return this._UYE_YONKURTARKYT;
			}
			set
			{
				if ((this._UYE_YONKURTARKYT != value))
				{
					this.OnUYE_YONKURTARKYTChanging(value);
					this.SendPropertyChanging();
					this._UYE_YONKURTARKYT = value;
					this.SendPropertyChanged("UYE_YONKURTARKYT");
					this.OnUYE_YONKURTARKYTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_YONKURNOKYT", DbType="VarChar(10)")]
		public string UYE_YONKURNOKYT
		{
			get
			{
				return this._UYE_YONKURNOKYT;
			}
			set
			{
				if ((this._UYE_YONKURNOKYT != value))
				{
					this.OnUYE_YONKURNOKYTChanging(value);
					this.SendPropertyChanging();
					this._UYE_YONKURNOKYT = value;
					this.SendPropertyChanged("UYE_YONKURNOKYT");
					this.OnUYE_YONKURNOKYTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_ODANO", DbType="VarChar(10)")]
		public string UYE_ODANO
		{
			get
			{
				return this._UYE_ODANO;
			}
			set
			{
				if ((this._UYE_ODANO != value))
				{
					this.OnUYE_ODANOChanging(value);
					this.SendPropertyChanging();
					this._UYE_ODANO = value;
					this.SendPropertyChanged("UYE_ODANO");
					this.OnUYE_ODANOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_BAKTIGIKIZ", DbType="Int")]
		public System.Nullable<int> UYE_BAKTIGIKIZ
		{
			get
			{
				return this._UYE_BAKTIGIKIZ;
			}
			set
			{
				if ((this._UYE_BAKTIGIKIZ != value))
				{
					this.OnUYE_BAKTIGIKIZChanging(value);
					this.SendPropertyChanging();
					this._UYE_BAKTIGIKIZ = value;
					this.SendPropertyChanged("UYE_BAKTIGIKIZ");
					this.OnUYE_BAKTIGIKIZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_KAYITTURU", DbType="VarChar(15)")]
		public string UYE_KAYITTURU
		{
			get
			{
				return this._UYE_KAYITTURU;
			}
			set
			{
				if ((this._UYE_KAYITTURU != value))
				{
					this.OnUYE_KAYITTURUChanging(value);
					this.SendPropertyChanging();
					this._UYE_KAYITTURU = value;
					this.SendPropertyChanged("UYE_KAYITTURU");
					this.OnUYE_KAYITTURUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_SONBEYANTRH", DbType="DateTime")]
		public System.Nullable<System.DateTime> UYE_SONBEYANTRH
		{
			get
			{
				return this._UYE_SONBEYANTRH;
			}
			set
			{
				if ((this._UYE_SONBEYANTRH != value))
				{
					this.OnUYE_SONBEYANTRHChanging(value);
					this.SendPropertyChanging();
					this._UYE_SONBEYANTRH = value;
					this.SendPropertyChanged("UYE_SONBEYANTRH");
					this.OnUYE_SONBEYANTRHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_UYRUK", DbType="VarChar(8)")]
		public string UYE_UYRUK
		{
			get
			{
				return this._UYE_UYRUK;
			}
			set
			{
				if ((this._UYE_UYRUK != value))
				{
					this.OnUYE_UYRUKChanging(value);
					this.SendPropertyChanging();
					this._UYE_UYRUK = value;
					this.SendPropertyChanged("UYE_UYRUK");
					this.OnUYE_UYRUKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_CEPTELEFON", DbType="VarChar(11)")]
		public string UYE_CEPTELEFON
		{
			get
			{
				return this._UYE_CEPTELEFON;
			}
			set
			{
				if ((this._UYE_CEPTELEFON != value))
				{
					this.OnUYE_CEPTELEFONChanging(value);
					this.SendPropertyChanging();
					this._UYE_CEPTELEFON = value;
					this.SendPropertyChanged("UYE_CEPTELEFON");
					this.OnUYE_CEPTELEFONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_AYRILISACIKLAMA", DbType="VarChar(100)")]
		public string UYE_AYRILISACIKLAMA
		{
			get
			{
				return this._UYE_AYRILISACIKLAMA;
			}
			set
			{
				if ((this._UYE_AYRILISACIKLAMA != value))
				{
					this.OnUYE_AYRILISACIKLAMAChanging(value);
					this.SendPropertyChanging();
					this._UYE_AYRILISACIKLAMA = value;
					this.SendPropertyChanged("UYE_AYRILISACIKLAMA");
					this.OnUYE_AYRILISACIKLAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_GNSACIKLAMA", DbType="VarChar(MAX)")]
		public string UYE_GNSACIKLAMA
		{
			get
			{
				return this._UYE_GNSACIKLAMA;
			}
			set
			{
				if ((this._UYE_GNSACIKLAMA != value))
				{
					this.OnUYE_GNSACIKLAMAChanging(value);
					this.SendPropertyChanging();
					this._UYE_GNSACIKLAMA = value;
					this.SendPropertyChanged("UYE_GNSACIKLAMA");
					this.OnUYE_GNSACIKLAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_GMAHALLE", DbType="NChar(10)")]
		public string UYE_GMAHALLE
		{
			get
			{
				return this._UYE_GMAHALLE;
			}
			set
			{
				if ((this._UYE_GMAHALLE != value))
				{
					this.OnUYE_GMAHALLEChanging(value);
					this.SendPropertyChanging();
					this._UYE_GMAHALLE = value;
					this.SendPropertyChanged("UYE_GMAHALLE");
					this.OnUYE_GMAHALLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_SIRANOG", DbType="NChar(10)")]
		public string UYE_SIRANOG
		{
			get
			{
				return this._UYE_SIRANOG;
			}
			set
			{
				if ((this._UYE_SIRANOG != value))
				{
					this.OnUYE_SIRANOGChanging(value);
					this.SendPropertyChanging();
					this._UYE_SIRANOG = value;
					this.SendPropertyChanged("UYE_SIRANOG");
					this.OnUYE_SIRANOGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UYE_SMSGRUP", DbType="NVarChar(50)")]
		public string UYE_SMSGRUP
		{
			get
			{
				return this._UYE_SMSGRUP;
			}
			set
			{
				if ((this._UYE_SMSGRUP != value))
				{
					this.OnUYE_SMSGRUPChanging(value);
					this.SendPropertyChanging();
					this._UYE_SMSGRUP = value;
					this.SendPropertyChanged("UYE_SMSGRUP");
					this.OnUYE_SMSGRUPChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
